[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.backends._legacy:_Backend"

[project]
name = "anomalyd"
version = "0.1.0"
description = "Free data anomaly detection"
requires-python = ">=3.10"
dependencies = ["sqlalchemy", "pyyaml", "click", "rich", "pandas", "numpy", "scipy", "scikit-learn", "prophet", "tabulate", "requests"]

[project.scripts]
anomalyd = "anomalyd.cli:cli"